global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets:
      - "localhost:9090"

  - job_name: "node"
    static_configs:
    - targets:
      # node-exporter
      - "localhost:9100"

  - job_name: "online_serving"
    scrape_interval: 5s
    static_configs:
    - targets:
      # model serving service
      - "localhost:8172"
